export const GET_LAUNCHES = "GET_LAUNCHES";
export const GET_SINGLE_LAUNCH = "GET_SINGLE_LAUNCH";
export const IS_VISIBLE = "IS_VISIBLE";
export const SET_TOGGLER_FALSE = "SET_TOGGLER_FALSE";
export const SEARCH_BY_YEAR = "SEARCH_BY_YEAR";
