export const GET_LAUNCHES = "GET_LAUNCHES";
export const GET_SINGLE_LAUNCH = "GET_SINGLE_LAUNCH";
export const IS_VISIBLE = "IS_VISIBLE";
export const SET_TOGGLER_FALSE = "SET_TOGGLER_FALSE";
export const GET_COMPANY_INFO = "GET_COMPANY_INFO";
